name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - 'BE/**'
      - 'snowflake-embedding/**'
      - '.github/workflows/docker-image.yml'
      - 'EXTRACTION/**'
      - 'INGESTION/**'


env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_RG: ${{ secrets.IBM_CLOUD_RG }}
  IBM_CLOUD_PROJECT: ${{ secrets.IBM_CLOUD_PROJECT }}
  ICR_REGION: ${{ secrets.ICR_REGION }}
  ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
  ICR_PASSWORD: ${{ secrets.ICR_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - path: BE
            image: us.icr.io/itz-watson-apps-q4mjqj3a-cr/fish-image-classify:latest
            app_name: fish-image-classify
          - path: snowflake-embedding
            image: us.icr.io/itz-watson-apps-q4mjqj3a-cr/snowflake-embedding-image:latest
            app_name: snowflake-embedding
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Install IBM Cloud Code Engine Plugin
        run: |
          ibmcloud plugin install code-engine
          
      - name: Install IBM Cloud CR Plugin
        run: |
          ibmcloud plugin install container-registry 

      - name: IBM Cloud CLI Login
        run: |
          ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}" -r us-south

      - name: set ICR region
        run: |
           ibmcloud cr region-set us-south

      - name: login ICR
        run: |
           ibmcloud cr login



      - name: Set IBM Cloud Resorce Group
        run: |
          ibmcloud target -g "${{ secrets.IBM_CLOUD_RG }}"
          

      - name: Set IBM Cloud Code Engine Project
        run: |
          ibmcloud ce project select --id "${{ secrets.IBM_CLOUD_PROJECT }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.context.image }} ${{ matrix.context.path }}

      - name: Push Docker image
        run: |
          docker push ${{ matrix.context.image }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy or Update Code Engine App
        env:
          app_name: ${{ matrix.context.app_name }}
          image_full: ${{ matrix.context.image }}
        run: |
          echo "APP NAME = $app_name"
          echo "IMAGE FULL = $image_full"
          application_exists=$(ibmcloud ce application list --output json | jq -r ".items[] | select(.metadata.name == \"${app_name}\") | .metadata.name")
          if [ "$application_exists" == "$app_name" ]; then
            echo "Updating application..."
            ibmcloud ce application update --name $app_name --cpu 2 --memory 8G --es 8G --min-scale 1 --env-from-secret $app_name -v public --image $image_full --port 8080 --registry-secret ibmcloud --wait-timeout 12000 --timeout 600 --probe-ready type=tcp --probe-ready port=8080
          else
            echo "Application does not exist, creating..."
            ibmcloud ce application create --name $app_name --cpu 2 --memory 8G --es 8G --min-scale 1 --env-from-secret $app_name -v public --image $image_full --port 8080 --registry-secret ibmcloud --wait-timeout 12000 --timeout 600 --probe-ready type=tcp --probe-ready port=8080
          fi
